window.PHASE4_INSIGHTS = {
  summary: {
    totalSessions: 219,
    phaseFourSessions: 58,
    phaseFourStart: "2026-02-25",
    phaseFourEnd: "2026-06-11",
    phaseFourSpanDays: 107,
    gapStart: "2025-12-23",
    gapEnd: "2026-02-25",
    gapDays: 64,
    sessionsPerWeek: 3.83,
  },
  monthlyCounts: [
    { month: "2024-09", count: 4 },
    { month: "2024-10", count: 20 },
    { month: "2024-11", count: 15 },
    { month: "2024-12", count: 9 },
    { month: "2025-01", count: 8 },
    { month: "2025-02", count: 3 },
    { month: "2025-03", count: 4 },
    { month: "2025-04", count: 1 },
    { month: "2025-05", count: 3 },
    { month: "2025-06", count: 6 },
    { month: "2025-07", count: 9 },
    { month: "2025-08", count: 17 },
    { month: "2025-09", count: 18 },
    { month: "2025-10", count: 17 },
    { month: "2025-11", count: 16 },
    { month: "2025-12", count: 11 },
    { month: "2026-01", count: 0 },
    { month: "2026-02", count: 3 },
    { month: "2026-03", count: 17 },
    { month: "2026-04", count: 16 },
    { month: "2026-05", count: 15 },
    { month: "2026-06", count: 7 },
  ],
  phaseFourMonthlyCounts: [
    { month: "2026-02", count: 3 },
    { month: "2026-03", count: 17 },
    { month: "2026-04", count: 16 },
    { month: "2026-05", count: 15 },
    { month: "2026-06", count: 7 },
  ],
  sessionSplit: [
    { name: "Push", count: 15, lastDate: "2026-06-08" },
    { name: "Pull", count: 16, lastDate: "2026-06-09" },
    { name: "Legs", count: 10, lastDate: "2026-06-04" },
    { name: "Upper", count: 17, lastDate: "2026-06-11" },
  ],
  recentSequence: [
    { date: "2026-05-23", name: "Legs" },
    { date: "2026-05-24", name: "Upper" },
    { date: "2026-05-25", name: "Push" },
    { date: "2026-05-27", name: "Pull" },
    { date: "2026-05-29", name: "Upper" },
    { date: "2026-05-31", name: "Legs" },
    { date: "2026-06-01", name: "Push" },
    { date: "2026-06-02", name: "Pull" },
    { date: "2026-06-04", name: "Legs" },
    { date: "2026-06-05", name: "Upper" },
    { date: "2026-06-08", name: "Push" },
    { date: "2026-06-09", name: "Pull" },
    { date: "2026-06-11", name: "Upper" },
  ],
  story: {
    lead:
      "Phase 4 is a four-session loop that comes back hard after a 64-day winter gap.",
    bullets: [
      "You logged 58 workouts in the phase-four block, averaging 3.83 sessions per week.",
      "The clearest wins are in leg drive and triceps/pulling load. Goblet squats and triceps pushdowns are the standout jumps.",
      "Several upper-body movements are getting heavier but not yet cleaner: rows, curls, and press variations are climbing in load while total reps sag.",
      "The log reads like two eras. Before the gap it is busy, then there is a dead zone, then Phase 4 restarts with a steadier four-day rhythm.",
    ],
    opinions: [
      "This looks like a strength-block story, not a hypertrophy-block story.",
      "You are progressing best when the movement is simple and fixed-path.",
      "The gap matters: the history is not one smooth curve, it is two separate runs.",
    ],
  },
  trendCards: [
    {
      session: "Legs",
      exercise: "Goblet Squat",
      direction: "up",
      firstDate: "2026-02-27",
      lastDate: "2026-06-04",
      firstBestWeight: 25,
      lastBestWeight: 90,
      deltaBestWeight: 65,
      firstVolume: 900,
      lastVolume: 1860,
      deltaVolume: 960,
      note: "Biggest jump in the block. Load moved hard while reps fell, which still reads as strong progression.",
    },
    {
      session: "Push",
      exercise: "Triceps Pushdown - Rope Attachment",
      direction: "up",
      firstDate: "2026-03-02",
      lastDate: "2026-06-08",
      firstBestWeight: 35,
      lastBestWeight: 80,
      deltaBestWeight: 45,
      firstVolume: 735,
      lastVolume: 960,
      deltaVolume: 225,
      note: "A clean overload story. The top set climbed a lot and the work stayed pretty tidy.",
    },
    {
      session: "Pull",
      exercise: "Wide-Grip Lat Pulldown",
      direction: "up",
      firstDate: "2026-02-25",
      lastDate: "2026-06-09",
      firstBestWeight: 65,
      lastBestWeight: 75,
      deltaBestWeight: 10,
      firstVolume: 1105,
      lastVolume: 1375,
      deltaVolume: 270,
      note: "The strongest pull progression. It is not flashy, but it keeps stepping forward.",
    },
    {
      session: "Legs",
      exercise: "Leg Extensions",
      direction: "up",
      firstDate: "2026-02-27",
      lastDate: "2026-06-04",
      firstBestWeight: 52.5,
      lastBestWeight: 67.5,
      deltaBestWeight: 15,
      firstVolume: 1102.5,
      lastVolume: 1257.5,
      deltaVolume: 155,
      note: "Quads are moving better, even though the total rep count has drifted down a little.",
    },
    {
      session: "Pull",
      exercise: "T-Bar Row with Handle each side independent",
      direction: "up",
      firstDate: "2026-04-08",
      lastDate: "2026-06-09",
      firstBestWeight: 25,
      lastBestWeight: 32.5,
      deltaBestWeight: 7.5,
      firstVolume: 400,
      lastVolume: 467.5,
      deltaVolume: 67.5,
      note: "Small but useful load gain. A good sign that the back work is still settling in.",
    },
    {
      session: "Push",
      exercise: "Machine Triceps Extension (drop sets)",
      direction: "up",
      firstDate: "2026-03-02",
      lastDate: "2026-06-08",
      firstBestWeight: 45,
      lastBestWeight: 50,
      deltaBestWeight: 5,
      firstVolume: 900,
      lastVolume: 1475,
      deltaVolume: 575,
      note: "Drop-set volume improved a lot. This looks workmanlike rather than dramatic, but it is clearly moving.",
    },
    {
      session: "Upper",
      exercise: "Seated Cable Rows",
      direction: "mixed",
      firstDate: "2026-02-27",
      lastDate: "2026-06-11",
      firstBestWeight: 70,
      lastBestWeight: 85,
      deltaBestWeight: 15,
      firstVolume: 1190,
      lastVolume: 1065,
      deltaVolume: -125,
      note: "Heavier, but not cleaner yet. The load is up while total work has slipped.",
    },
    {
      session: "Upper",
      exercise: "Machine Bicep Curl",
      direction: "mixed",
      firstDate: "2026-02-27",
      lastDate: "2026-06-11",
      firstBestWeight: 50,
      lastBestWeight: 67.5,
      deltaBestWeight: 17.5,
      firstVolume: 1250,
      lastVolume: 1122.5,
      deltaVolume: -127.5,
      note: "Arms are getting stronger at the top end, but the set quality still has wobble.",
    },
    {
      session: "Push",
      exercise: "Incline Dumbbell Press",
      direction: "mixed",
      firstDate: "2026-03-02",
      lastDate: "2026-06-08",
      firstBestWeight: 17.5,
      lastBestWeight: 25,
      deltaBestWeight: 7.5,
      firstVolume: 630,
      lastVolume: 250,
      deltaVolume: -380,
      note: "This reads like overload pressure, not a dead lift. The current work is heavier but much less complete.",
    },
    {
      session: "Legs",
      exercise: "Leg Press",
      direction: "mixed",
      firstDate: "2026-02-27",
      lastDate: "2026-06-04",
      firstBestWeight: 80,
      lastBestWeight: 100,
      deltaBestWeight: 20,
      firstVolume: 1920,
      lastVolume: 1000,
      deltaVolume: -920,
      note: "The top weight climbed, but this has not turned into stable work capacity yet.",
    },
    {
      session: "Upper",
      exercise: "Chest Fly (machine)",
      direction: "down",
      firstDate: "2026-02-27",
      lastDate: "2026-06-11",
      firstBestWeight: 98,
      lastBestWeight: 88,
      deltaBestWeight: -10,
      firstVolume: 1274,
      lastVolume: 1232,
      deltaVolume: -42,
      note: "The one clear recent regression in the upper body block.",
    },
  ],
};
